version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      
  pre_build:
    commands:
      - echo Installing npm packages...
      - npm install
      
  build:
    commands:
      - echo Building React application...
      - npm run build
      
  post_build:
    commands:
      - echo Build completed successfully
      - echo Invalidating CloudFront distribution $CLOUDFRONT_DISTRIBUTION_ID
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: dist
  name: medalfoundation-build-$(date +%Y-%m-%d)
